[package]
name = "mica-hl"
description = "High-level interface to the Mica scripting language"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/liquidev/mica"

[dependencies]
mica-language = { version = "0.2.0", path = "../mica-language" }
