[package]
name = "mica"
description = "A user-friendly embeddable scripting language"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
   "mica-cli",
   "mica-hl",
   "mica-language",
   "mica-std",
]

[dependencies]
mica-hl = { path = "mica-hl" }
mica-std = { path = "mica-std" }

[profile.release]
debug = 1
