[package]
name = "mica"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "9.1.2"
phf = { version = "0.10.1", features = ["macros"] }
structopt = "0.3.26"
