[package]
name = "mica"
description = "A user-friendly embeddable scripting language"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
   "mica-cli",
   "mica-language",
]

[dependencies]
mica-language = { path = "mica-language" }

[profile.release]
debug = 1
