[package]
name = "mica"
version = "0.1.0"
edition = "2021"

[dependencies]
rustyline = "9.1.2"
phf = { version = "0.10.1", features = ["macros"] }
structopt = "0.3.26"
bytemuck = "1.8.0"

[profile.release]
debug = 1
