[package]
name = "mica"
description = "A simple, user-friendly, embeddable scripting language"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/liquidev/mica"
keywords = ["language", "scripting", "embeddable"]
categories = ["compilers"]

[workspace]
members = [
   "mica-cli",
   "mica-hl",
   "mica-language",
   "mica-std",
]

[dependencies]
mica-hl = { version = "0.1.0", path = "mica-hl" }
mica-std = { version = "0.1.0", path = "mica-std" }

[profile.release]
debug = 1
