[package]
name = "mica-language"
description = "Reference implementation of the Mica scripting language"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/liquidev/mica"

[dependencies]
bytemuck = "1.8.0"
